[package]
name = "google-plus-posts-dumper"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.1"
html5ever = "0.27.0"
markup5ever_rcdom = "0.3.0"
markup5ever = "0.12.1"
chrono = "0.4.42"
html-escape = "0.2.13"
